name: "Lint"
description: "Lints targeted OSCAL files for schema compliance"

inputs:
  oscal-target:
    description: "The target file to be linted"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        # Sets up array of targets
        IFS=' ' read -r -a targets <<< "${{ inputs.oscal-target }}"

        # Loop through each file and lint
        for target in "${targets[@]}"; do
          # Check if the file exists
          if [ ! -f "$target" ]; then
            echo "File $target does not exist"
            continue
          fi

        # Check if the file exists
        if [ ! -f "$target" ]; then
          echo "File $target does not exist"
          exit 1
        fi

        # Lint the file with Lula
          echo "Linting $target"
          lula tools lint -f "$target"
        done
