name: "Validate"
description: "Performs the Lula validation and evaluation"

inputs:
  oscal-file:
    description: "The file file to be validated"
  threshold:
    description: "The assessment result file to compare against. Attempts to find assessment-results.yaml if not specified"
  target:
      description: "The framework prop to target"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
       #!/bin/bash
        # Base url for lula artifacts
        file_dir="${HOME}/.lula-cache"
        threshold="${{ inputs.threshold }}"
        file="${{ inputs.oscal-file }}"
        target="${{ inputs.target }}"

        # Check if the file exists
        if [ ! -f "$file" ]; then
          echo "File $file does not exist"
          exit 1
        fi

        # Check if the threshold variable is empty - otherwise use the threshold
        if [ -z "$threshold" ]; then
          if [ -n "$target" ]; then
            lula validate -f "$file" -o "$file_dir/assessment-results.yaml -t "$target""
          else
            lula validate -f "$file" -o "$file_dir/assessment-results.yaml"
          fi
          # Check if default assessment results file exists
          if [ -f "assessment-results.yaml" ]; then
            if [ -n "$target" ]; then
              lula evaluate -f assessment-results.yaml -f "$file_dir/assessment-results.yaml -t "$target""
            else
              lula evaluate -f assessment-results.yaml -f "$file_dir/assessment-results.yaml"
            fi
          else
            echo "No threshold exists - will not perform evaluation"
            # exiting zero here currently - could be worth exiting non-zero
            exit 0
          fi
        else
          if [ -n "$target" ]; then
            lula validate -f "$file" -o "$file_dir/assessment-results.yaml -t "$target""
            lula evaluate -f "$threshold" -f "$file_dir/assessment-results.yaml -t "$target""
          else
            lula validate -f "$file" -o "$file_dir/assessment-results.yaml"
            lula evaluate -f "$threshold" -f "$file_dir/assessment-results.yaml"
          fi
        fi
