name: "Validate"
description: "Performs Lula Validate"

inputs:
  component-definition:
    description: "The component-definition file to be validated"
  assessment-result:
    description: "The output location of the assessment result file. Defaults to ./assessment-results.yaml if not specified"
  target:
    description: "The framework prop to target"
  options:
    description: "Any additional flag options"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
       #!/bin/bash
        assessment-result="${{ inputs.assessment-result }}"
        component-definition="${{ inputs.component-definition }}"
        target="${{ inputs.target }}"
        options="${{ inputs.options }}"

        # Check if the component-definition exists
        if [ ! -f "$component-definition" ]; then
          echo "Component Definition does not exist"
          exit 1
        else
          # Check if assessment-result output is set
          if [ -z "$assessment-result" ]; then
           assessment-result="./assessment-results.yaml"
          fi
          if [ -n "$target" ]; then
            if [ -n "$options" ]; then
              lula validate -f "$component-definition" -t "$target" -o "$assessment-result" "$options"
            else
              lula validate -f "$component-definition" -t "$target" -o "$assessment-result"
            fi
          else
            if [ -n "$options" ]; then
              lula validate -f "$component-definition" -o "$assessment-result" "$options"
            else
              lula validate -f "$component-definition" -o "$assessment-result"
            fi
          fi
