name: "Evaluate"
description: "Performs the Lula Evaluation"

inputs:
  assessment-result:
    description: "The assessment result file to be Evaluated against the Threshold or contains two results to Evaluate"
  threshold:
    description: "The assessment result file to be compared against. Attempts to find assessment-results.yaml if not specified"
  target:
    description: "The framework prop to target"
  options:
    description: "Any additional flag options"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        # Base url for lula artifacts
        file_dir="${HOME}/.lula-cache"
        threshold="${{ inputs.threshold }}"
        file="${{ inputs.assessment-result }}"
        target="${{ inputs.target }}"
        options="${{ inputs.options }}"

        # Determine if assessment-results.yaml exists
        if [ -z "$threshold" ] && [ -z "$file" ] && [ ! -f "assessment-results.yaml" ]; then
          echo "no assessment results found"
          exit 1
        fi

        # Set default threshold to assessment-results.yaml if threshold is not provided and the file exists
        if [ -z "$threshold" ] && [ -f "assessment-results.yaml" ]; then
          threshold="assessment-results.yaml"
        fi

        # Evaluate based on the available inputs
        if [ -n "$threshold" ] && [ -n "$file" ]; then
          if [ -n "$target" ]; then
            if [ -n "$options" ]; then
              lula evaluate -f "$threshold" -f "$file" -t "$target" "$options"
            else
              lula evaluate -f "$threshold" -f "$file" -t "$target"
            fi
          else
            if [ -n "$options" ]; then
              lula evaluate -f "$threshold" -f "$file" "$options"
            else
              lula evaluate -f "$threshold" -f "$file"
            fi
          fi
        elif [ -n "$threshold" ]; then
          if [ -n "$target" ]; then
            if [ -n "$options" ]; then
              lula evaluate -f "$threshold" -t "$target" "$options"
            else
              lula evaluate -f "$threshold" -t "$target"
            fi
          else
            if [ -n "$options" ]; then
              lula evaluate -f "$threshold" "$options"
            else
              lula evaluate -f "$threshold"
            fi
          fi
        elif [ -n "$file" ]; then
          if [ -n "$target" ]; then
            if [ -n "$options" ]; then
              lula evaluate -f "$file" -t "$target" "$options"
            else
             lula evaluate -f "$file" -t "$target"
            fi
          else
            if [ -n "$options" ]; then
              lula evaluate -f "$file"
            else
              lula evaluate -f "$file"
            fi
          fi
        else
          echo "no assessment results to compare"
          exit 1
        fi
