name: setup-go
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/lula extractVersion="^go (.*)$" versioning=semver-coerced
        go-version-file: defenseunicorns/lula/go.mod
        cache: true
